server:
  port: 8085

spring:
  application:
    name: song-process-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER:musicdreamer}
    password: ${RABBITMQ_PASS:music123456}
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: auto

logging:
  level:
    com.musicdreamer: DEBUG
